name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1
    - name: Build and Push App Image.
      uses: docker/build-push-action@v1
      with:
        username: td4b
        password: ${{ secrets.GITLAB_TOKEN }}
        registry: registry.gitlab.com
        repository: td4b/images/gocryptapp
        tag_with_ref: true

    - name: Navigate to DB Docker Build dir.
      run: cd database

    - uses: docker/setup-buildx-action@v1
    - name: Build and Push DB Image.
      uses: docker/build-push-action@v1
      with:
        username: td4b
        password: ${{ secrets.GITLAB_TOKEN }}
        registry: registry.gitlab.com
        repository: td4b/images/gocryptdb
        tag_with_ref: true
